apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: weerstandnatuursteen-frontend-tls
  labels:
    app: weerstandnatuursteen-frontend
spec:
  secretName: ${INGRESS_TLS_SECRET}
  dnsNames:
    - weerstandnatuursteen.nl
    - www.weerstandnatuursteen.nl
    - backend.weerstandnatuursteen.nl
    - www.backend.weerstandnatuursteen.nl
  issuerRef:
    kind: ClusterIssuer
    name: ${CERT_MANAGER_CLUSTER_ISSUER}
